/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.Telas;

import oshi.SystemInfo;
import oshi.hardware.CentralProcessor;

/**
 *
 * @author manoel
 */
public class Info extends javax.swing.JPanel {

    SystemInfo si = new SystemInfo();
    CentralProcessor.ProcessorIdentifier cpu = si.getHardware().getProcessor().getProcessorIdentifier();
    
    /**
     * Creates new form Info
     */
    public Info() {
        initComponents();
        
        lblOperatingSystem.setText(si.getOperatingSystem().toString());
        lblCPUName.setText(cpu.getName());
        lblCPUIdentifier.setText(cpu.getIdentifier());
        lblCPUMicroArchtecture.setText(cpu.getMicroarchitecture());
        lblCPUVendor.setText(cpu.getVendor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblOperatingSystem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCPUVendor = new javax.swing.JLabel();
        lblCPUMicroArchtecture = new javax.swing.JLabel();
        lblCPUIdentifier = new javax.swing.JLabel();
        lblCPUName = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 29, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Operating system:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lblOperatingSystem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOperatingSystem.setForeground(new java.awt.Color(0, 153, 153));
        lblOperatingSystem.setText(":");
        jPanel1.add(lblOperatingSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 270, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Processor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblCPUVendor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCPUVendor.setForeground(new java.awt.Color(0, 153, 153));
        lblCPUVendor.setText(":");
        jPanel1.add(lblCPUVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 370, -1));

        lblCPUMicroArchtecture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCPUMicroArchtecture.setForeground(new java.awt.Color(0, 153, 153));
        lblCPUMicroArchtecture.setText(":");
        jPanel1.add(lblCPUMicroArchtecture, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 380, -1));

        lblCPUIdentifier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCPUIdentifier.setForeground(new java.awt.Color(0, 153, 153));
        lblCPUIdentifier.setText(":");
        jPanel1.add(lblCPUIdentifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 370, -1));

        lblCPUName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCPUName.setForeground(new java.awt.Color(0, 153, 153));
        lblCPUName.setText(":");
        jPanel1.add(lblCPUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 360, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 290));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPUIdentifier;
    private javax.swing.JLabel lblCPUMicroArchtecture;
    private javax.swing.JLabel lblCPUName;
    private javax.swing.JLabel lblCPUVendor;
    private javax.swing.JLabel lblOperatingSystem;
    // End of variables declaration//GEN-END:variables
}
